#!/bin/bash

# This script ties together the raspistill and raspivid utilities
# to allow more convenient control of the RasPi camera when taking
# multiple pictures.  No doubt this replicates features implemented
# elsewhere, but I wanted to finally write a shell script.
# 
# The script will prompt for an email address for any pictures taken
# in a session. mpack is used to send the email with the picture as
# an attachment, and so must be configured (/etc/ssmtp/ssmtp.conf).
# The email address is not currently checked in any way, beyond
# seeing if a string was entered, so make sure you don't mess it up.
#
# Current implemented behavior:
#
#   press 'p' to take a picture.
#   press 'q' to quit.
#
# Credit to Franklin52 on the unix.com forums for the keypress polling
# code.  The remainder of the script was written by Alex J. Ponting.

_send-picture() {
  # Creates and attempts to email an image to a provided
  # email address.
  
  OF=$2/microscope-image-$(date +%s).png
  raspistill -o $OF -w 1920 -h 1080

  echo "sending email..."
  mpack -s "Microscope Picture" $OF $1
  echo "finished send attempt!"
}

_key-press() {
  # Detects a key press, and returns the pressed key.

  local kp
  ESC=$'\e'
  _KEY=
  read -d '' -sn1 _KEY
  case $_KEY in
    "$ESC")
       while read -d '' -sn1 -t1 kp
       do
	 _KEY=$_KEY$KP
         case $kp in
           [a-zA-NP-Z~]) break;;
         esac
       done
    ;;
  esac
  printf -v "${1:-_KEY}" "%s" "$_KEY"
}

_end-vid() {
  # Kill a raspivid instance silently.
  
  VID_PROC=$(ps | grep "raspivid" &)
  VID_ID=${VID_PROC:1:4}
  kill -9 $VID_ID &
}

# The actual meat.  Collects an email address, starts up
# a raspivid instance, then waits for keypress to kill
# raspivid, take a picture, then bring raspivid back up.
# Suuuuper elegant and def. not a hack at all.

clear

ODIR=$HOME/img/$(date +%Y-%m-%d)
mkdir $ODIR 2> /dev/null

echo "To what email address should I send pictures?"
read EMAIL
while [ -z $EMAIL ]; do
  echo "Gotta give me something!"
  read EMAIL
done
echo "Thanks, I'll send pictures to $EMAIL"

echo "Starting camera... "
raspivid -t 0 -fps 25.2 &

while [ 1 = 1 ]; do
  
  _key-press key

  if [ $key = 'p' ]; then
    _end-vid
    _send-picture $EMAIL $ODIR

    raspivid -t 0 -fps 25.2 &
  fi

  if [ $key = 'q' ]; then
    _end-vid
    echo "Done and done."
    exit
  fi

done
